spring:
  application:
    name: springcloud-tzh-feign-hystrix
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.itmuch.cloud.feign.UserFeignClient: DEBUG
feign:
  hystrix:
    enabled: true # 开启Feign熔断
  httpclient:
    enabled: true
management: # 检查health需要配置
  endpoint:
    health:
      show-details: always
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
