server:
  port: 7900
spring:
  application:
    name: springcloud-tzh-ribbon-with-hystrix-propagation
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management: # 检查health需要配置
  endpoint:
    health:
      show-details: always