server:
  port: 7902
spring:
  application:
    name: springcloud-tzh-ribbon
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
springcloud-tzh-user: # 提供者yml中的application: name: springcloud-tzh-user
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule