server:
  port: 8090
eureka:
  client:
    service-url:
      default-zone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: springcloud-tzh-gateway-zuul
